NAME: 'data100_ac3_sparse5_long234927_model_SCPN0.1'

MODEL:
    model_type: 'superhuman'  # 'mala' or 'superhuman'
    input_nc: 1
    output_nc: 12
    dropout: 0.1
    if_sigmoid: True
    # for 'mala':
    init_mode_mala: 'kaiming'
    # for 'superhuman':
    if_skip: 'False'
    filters: 
        - 28
        - 36
        - 48
        - 64
        - 80
    emd: 16
    upsample_mode: 'bilinear'  # 'bilinear', 'nearest', 'transpose', 'transposeS'
    decode_ratio: 1
    merge_mode: 'add'  # 'add', 'cat'
    pad_mode: 'zero'  # 'zero', 'replicate'
    bn_mode: 'async'  # 'sync', 'async'
    relu_mode: 'elu'  # 'elu', 'relu', 'leaky'
    init_mode: 'kaiming_normal'  # 'kaiming_normal', 'kaiming_uniform', 'xavier_normal', 'xavier_uniform'
    pre_train: False
    trained_gpus: 1
    pre_train_mode: 'finetune'  # 'finetune', 'extract_feature'
    trained_model_name: '2020-12-21--08-27-49_ssl_suhu_noskip_mse_lr0001_snemi3d_ulb5'
    trained_model_id: 400000

TRAIN:
    resume: False
    if_valid: True
    if_seg: True
    model_id:
        - 1000
        - 5000
        - 10000
        - 15000
        - 20000
    model_path: '/braindat/lab/liuxy/sparse_annotation/SPOCO/EM_3d/models/2022-09-04--03-18-31_data100_ac3_sparse5_long234927_aff10_embw10_psdw1_ctw0_batch2_crossori_thresAuto_modeling_entropy_percent0.005'
    cache_path: '../caches/'
    cache_path2: '../output/caches2/'
    save_path: '../models/'
    pad: 0
    loss_func: 'WeightedMSELoss'   # 'WeightedBCELoss', 'BCELoss'
    if_verse: False
    separate_weight: False
    embedding_mode: 1  # 1 or 5 different shifts [1, 1, 1, 2, 3, 3, 3, 9, 9, 4, 27, 27]
    aff_thres: 0.5
    affs0_weight: 10.0
    emb_weight: 10.0
    pseudo_weight: 1.0
    ct_weight: 0.0
    opt_type: 'adam'
    total_iters: 200000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 100
    valid_freq: 1000
    save_freq: 1000
    decay_iters: 100000
    weight_decay: ~
    power: 1.5

    batch_size: 2
    batch_size_un: 2
    num_workers: 2
    if_cuda: True

    random_seed: 555  # -1 is none

DATA:
    if_sparse: True
    sparse_id: 5
    dataset_name: 'ac3'  # 'snemi3d-ac3', 'cremi-A', 'cremi'
    unlabel_dataset: 'ac3_ac4'  # 'ac3_ac4', 'ac4_around', 'cremi-C-200', 'cremi-all'
    unlabel_split: 100
    train_split: 100
    test_split: 50
    data_folder: '../data100'
    padding: 50
    shift_channels: [[-1,0,0],
                     [0,-1,0],
                     [0,0,-1],
                     [-2,0,0],
                     [0,-3,0],
                     [0,0,-3],
                     [-3,0,0],
                     [0,-9,0],
                     [0,0,-9],
                     [-4,0,0],
                     [0,-27,0],
                     [0,0,-27]]
    shift: ~
    if_dilate: True
    widen_way: True
    if_scale_aug: False
    if_filp_aug: True
    if_rotation_aug: True
    if_intensity_aug: True
    if_elastic_aug: True
    scale_factor: 1.5
    min_noise_std: 0.01
    max_noise_std: 0.2
    min_kernel_size: 3
    max_kernel_size: 9
    min_sigma: 0
    max_sigma: 2
    per_mode: 1
    if_norm_images: False
    if_scale_aug_unlabel: False
    if_filp_aug_unlabel: False
    if_rotation_aug_unlabel: False
    if_intensity_aug_unlabel: True
    if_noise_aug_unlabel: True
    if_blur_aug_unlabel: True
    if_mask_aug_unlabel: True
    if_sobel_aug_unlabel: False
    if_mixup_aug_unlabel: False
    if_misalign_aug_unlabel: True
    if_elastic_aug_unlabel: False
    if_artifact_aug_unlabel: False
    if_missing_aug_unlabel: False
    if_blurenhanced_aug_unlabel: False


TEST:
    pad: 0
    model_name: ''